name: CoopeticoTaxiApp
description: Aplicaci칩n m칩vil para taxistas de Coopetico.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0 #Para realizar http requests.
  shared_preferences: ^0.5.2 #Para almacenar el token del usuario en el dispositivo.

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  google_maps_flutter: #Dependencia para trabajar con Google Maps
    path: ./vendors/google_maps_flutter
  # Location
  location: ^2.0.0

  stomp_client: ^0.0.2
   # git:
    #  url: git://github.com/kevinjimenez96/stomp_client.git

  flare_flutter: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3 # Dependencia para unit tests en dart
               # Es una versi칩n m치s vieja para que sea compatible con la version de flutter.
  mockito: ^4.0.0 # Dependencia para hacer mocks en las pruebas.
  test_api: ^0.2.2

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - taxi.png
  - Loading.flr
